version: '3.8'

services:
  postgresql:
    image: postgres:9-alpine
    environment:
        - POSTGRES_PASSWORD=test1234
        - POSTGRES_USER=mmsuser
        - POSTGRES_DB=mms
    ports:
      - 5432:5432
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
        - "discovery.type=single-node"
    ports:
        - 9200:9200
        - 9300:9300
  gradle:
    container_name: my_container
    build: .
    depends_on:
        - postgresql
        - elasticsearch