version: '3.8'

services:
  postgres:
    image: postgres:9-alpine
    environment:
        - POSTGRES_PASSWORD=test1234
        - POSTGRES_USER=mmsuser
        - POSTGRES_DB=mms
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - "discovery.type=single-node"
    ports:
        - 9200:9200
        - 9300:9300

  mms:
    build: .
    environment:
        - "SPRING_PROFILES_ACTIVE=test"
    networks:
      mms_default:
        aliases:
          - mms1
    depends_on:
        - postgres
        - elasticsearch
    ports: 
        - 8080:8080