version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install -g newman
            - run: newman run crud.postman_collection.json -e localhost-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build-and-test