version: 2.1
orbs:
 newman: postman/newman@0.0.2
jobs:
  build-and-test:
    executor:
      name: newman/postman-newman-docker
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run: cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: docker-compose up --build -d
      - run: docker-compose ps
      - run: sleep 2m
      - newman/newman-run:
          collection: cd example; crud.postman_collection.json -e test-env.json --delay-request 300
  #- run: cd example; crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: sudo npm install -g newman
      #- run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: sudo npm install -g newman
      #- run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test