version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: cd ~/mms && cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: cd ~/mms && docker-compose build
      - run: cd ~/mms && docker-compose run -d -p 8080 --name mms_mms_1 mms
      - run: cd ~/mms && docker ps
      - run: 
          command: |
            mkdir tst
            docker pull postman/newman
            docker run --network mms_default -t postman/newman ~/mms/example/crud.postman_collection.json -e  ~/mms/example/test-env.json --delay-request 300
      #docker create -v /tst --name test mms_mms:latest /bin/true
      #docker cp ~/mms/example/ test:/tst/
      #docker cp ~/mms/example/test-env.json mms_mms_1:/mms/example/test-env.json
      #docker run --volumes-from test -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #docker create -v /tst --name test mms_mms:latest
      #docker cp example/test-env.json test:/tst/test-env.json 
     #- run: cd ~/mms && docker run --network container:mms_mms_1 appropriate/curl --connect-timeout 30 --retry 300 --retry-delay 10 --retry-connrefused http://localhost:8080
     # - run cd ~/mms && docker exec mms_mms_1 curl --retry 30 --retry-delay 10 --retry-connrefused http://localhost:8080
     # - run: 
     #     command: |
     #       cd ~/mms/example
     #       sudo npm install -g newman
     #       sudo newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
#        - run: 
 #         command: | 
  #            docker pull postman/newman
  #            cd ~/mms/example
   #           docker run -v ~/mms/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300