version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
    build: 
        machine: true
        steps:
            #- setup_remote_docker
            - checkout
            #- setup_remote_docker
            - run:
                name: Install Docker Compose
                command:
                    curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                    chmod +x ~/docker-compose
                    sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - run: docker-compose up --build; cp application.properties.example application.properties
    test:
        executor:
            name: node/default
        steps:
            - checkout
            - run: sudo npm install -g newman 
            - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: sudo npm install -g newman
      #- run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build
        - test