version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: cd ~/mms && cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: cd ~/mms && docker-compose build
      #- run: cd ~/mms && docker run -p 8080 --name mms_mms_1 mms_mms:latest --network="bridge" 
      - run: cd ~/mms && docker-compose run -d -p 8080 --name mms_mms_1 mms
      - run: cd ~/mms && sleep 2m
      #- run: cd ~/mms && docker network ls
      #- run: cd ~/mms && docker network inspect mms_default
      - run: cd ~/mms && docker ps
      - run: 
          command: | 
            docker pull postman/newman
            cd ~/mms/example
            docker cp ~/mms/example/test-env.json ${DOCKER_HOST}:/mms/example/test-env.json
            docker run --network mms_default -v ${DOCKER_HOST}:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: docker inspect mms_mms_1 
      #- run: docker inspect mms_postgres_1
      #- run: docker inspect mms_elasticsearch_1
      #scp user@host:/path/to/file /local/path
     # scp -r ~/mms/example/test-env.json DOCKER_MACHINE_NAME:/mms/example/test-env.json
      #docker cp ~/mms/example/test-env.json mms_mms_1:/mms/example/test-env.json
      #docker run --volumes-from test -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #docker create -v /tst --name test mms_mms:latest
      #docker cp example/test-env.json test:/tst/test-env.json 
     #- run: cd ~/mms && docker run --network container:mms_mms_1 appropriate/curl --connect-timeout 30 --retry 300 --retry-delay 10 --retry-connrefused http://localhost:8080
     # - run cd ~/mms && docker exec mms_mms_1 curl --retry 30 --retry-delay 10 --retry-connrefused http://localhost:8080
     # - run: 
     #     command: |
     #       cd ~/mms/example
     #       sudo npm install -g newman
     #       sudo newman run crud.postman_collection.json -e test-env.json --delay-request 300
     #docker cp mms_mms_1:~/example/test-env.json /etc/newman
     #docker cp ~/mms/example/test-env.json mms_mms_1:/etc/newman
     #docker cp mms_mms_1:/example/test-env.json ~/mms/example
    #docker pull postman/newman
    #docker create -v /mms/tst --name test mms_mms:latest /bin/true
      #- run: cd ~/mms; docker pull postman/newman
      #- run: cd example; docker pull postman/newman; docker run --network="bridge" -v ~/mms/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
#        - run: 
 #         command: | 
  #            docker pull postman/newman
  #            cd ~/mms/example
   #           docker run -v ~/mms/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300