version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
        # specify the version you desire here
        - image: circleci/openjdk:jdk11
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up --build; cp application.properties.example application.properties
      
  test:
    executor: 
      name: node/default
    steps:
        - checkout
        - run: sudo npm install -g newman; cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: sudo npm install -g newman
      #- run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    version: 2

    build-and-test:
        jobs:
        - build
        - test