version: 2
orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: "Build"
      #- image: cimg/<language>:<version TAG>
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up --build; cp application.properties.example application.properties
  test:
    executor:
      name: node/default
    #docker:
      #- image: cimg/<language>:<version TAG>
    steps:
      - checkout
      - run: sudo npm install -g newman
      - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test