version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Create and start all services from the docker-compose configuration."
          command: |
            cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
            docker-compose build
            docker-compose run -d --name mms_mms_1 mms
      - run: sleep 30s
      - run: 
          name: "Run and test Postman Collection."
          command: |
            cd ~/mms/example
            IP_VAR=`docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mms_mms_1`
            sed -i "s/localhost/$IP_VAR/" test-env.json
            docker create -v /tst --name mms_test_configs alpine:3.4 /bin/true
            docker cp ~/mms/example/. mms_test_configs:/tst
            docker run --volumes-from mms_test_configs --link mms_mms_1 --network=mms_defualt -t postman/newman run /tst/crud.postman_collection.json -e /tst/test-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build-and-test