version: 2.1
orbs:
  node: circleci/node@1.1.6
  newman: postman/newman@0.0.2
jobs:
  build:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: docker-compose up --build
      - run: docker-compose ps    
  test:
    executor:
      name: newman/postman-newman-docker
    steps:
      - checkout
      - run: sleep 3m
      #- run: cd example
      - newman/newman-run: 
          collection: crud.postman_collection.json
          environment: ./example.test-env.json
          delay-request: '300'
      #test-env.json --delay-request 300
  #test:
    #executor: 
      #name: node/default
    #steps:
        #- checkout
        #- run: sudo npm install -g newman; cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: sudo npm install -g newman
      #- run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    version: 2

    build-and-test:
        jobs:
        - build
        - test