version: 2.1
#orbs:
  #node: circleci/node@1.1.6
  #newman: postman/newman@0.0.2
jobs:
    build: 
        machine: true
        working_directory: ~/mms
        steps:
            - checkout
            - run: 
                name: Install Docker Compose
                command: |
                    set -x
                    sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
            - run: cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
            #- run: docker-compose up --build -d
            #- run: sleep 3m
            #- run: sudo apt-get update
            #- run: sudo apt-get install nodejs
            #- run: sudo apt-get install npm
            - run: docker pull postman/newman
            #- run: docker run -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
            - run: docker run -v ~/mms:example/crud.postman_collection.json -t postman/newman \
                --environment="test-env.json" \
                --delay-request="300"
            #- run: docker run -v ~/collections:/etc/newman -t postman/newman:alpine HTTPBinNewmanTest.json.postman_collection
            #- run: 
                #name: "Installing Node"
                #command: |
                    #curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
                    #sudo apt install nodejs
            #- run: sudo npm install -g newman
           # - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
            #- run: docker inspect mms_mms_1
            #- run: docker inspect mms_postgres_1
            #- run: docker-compose ps
    #test:
        #executor:
            #name: newman/postman-newman-docker
        #steps:
          #- checkout
          #- run: sleep 3m
          #- run: cd example
          #- newman/newman-run: 
              #collection: example/crud.postman_collection.json
              #environment: example/test-env.json
              #delay-request: '300'
workflows:
    version: 2
    build-and-test:
      jobs:
        - build
        #- test
            #requires:
               # - build 