version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
    build: 
        machine: true
        working_directory: ~/mms
        steps:
            - checkout
            #- setup_remote_docker
            - run: 
                name: Install Docker Compose
                command: |
                    set -x
                    curl -L https://github.com/docker/compose.git `uname -s`-`uname -m` > /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
            - run: docker-compose up --build; cp application.properties.example application.properties
    test:
        executor:
            name: node/default
        steps:
            - checkout
            - run: sudo npm install -g newman 
            - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build
        - test
            #requires:
                #- build 