version: 2.1
#orbs:
  #node: circleci/node@1.1.6
jobs:
    build: 
        machine: true
        working_directory: ~/mms
        steps:
            - checkout
            #- setup_remote_docker
            - run: 
                name: Install Docker Compose
                command: |
                    set -x
                    sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
            #- run: setup_remote_docker
            - run: cp ./example/src/main/resources/application.properties.example /example/src/main/resources/application.properties 
            - run: docker-compose build
            - run: docker-compose up -p mms
    test:
        machine: true
        #docker:
            #image: postman/newman:latest
        steps:
            - checkout
            - run: sudo npm install -g newman 
            - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    version: 2
    build-and-test:
      jobs:
        - build
        - test:
            requires:
                - build 