#version: 2.1
jobs:
    build:
        steps:
            - checkout
            - setup_remote_docker
            - run: docker-compose up --build; cp application.properties.example application.properties
    test:
        steps:
            - checkout
            - run: sudo npm install -g newman
            - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300