version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
    build: 
        docker:
            - image: postgres:9-alpine
        steps:
            - checkout
            - setup_remote_docker
            - run: install docker-compose
            - run: docker-compose up --build; cp application.properties.example application.properties
    test:
        executor:
            name: node/default
        steps:
            - checkout
            - run: sudo npm install -g newman 
            - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: sudo npm install -g newman
      #- run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build
        - test