version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: docker-compose build
      - run: docker-compose up
      - run: sleep 2m
      #- run: docker-compose up -d
      - run: docker-compose ps
      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run -d --name mms_mms mms_mms
            docker exec mms_mms_1 curl --retry 10 --retry-connrefused http://localhost:8080
      - run: docker-compose ps
      #- run: sleep 3m
      #- run: sudo npm install -g newman
      #- run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build-and-test