version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - setup_remote_docker
      - run: docker-compose up --build
      - checkout
      #- node/with-cache:
          #steps:
      - run: sudo npm install -g newman
      - run: cd example; newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build-and-test