version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: docker-compose build
      - run: docker-compose run -d -p 8080 --name mms_mms_1 mms
      - run: docker ps
      - run: sleep 2m
      - run: 
          command: |
            docker create -v /tst --name mms_test_configs alpine:3.4 /bin/true
            docker cp ~/mms/example/. mms_test_configs:/tst
            docker run --add-host=${DOCKER_HOST}:8080 --volumes-from mms_test_configs --network="container:mms_mms_1" -t postman/newman run /tst/crud.postman_collection.json -e /tst/test-env.json --delay-request 300
            docker network inspect mms_default
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
#        - run: 
 #         command: | 
  #            docker pull postman/newman
  #            cd ~/mms/example
   #           docker run -v ~/mms/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300