version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: cd ~/mms && cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: cd ~/mms && docker-compose build
      #- run: cd ~/mms && docker run -p 8080 --name mms_mms_1 mms_mms:latest --network="bridge" 
      - run: cd ~/mms && docker-compose run -d -p 8080 --name mms_mms_1 mms
      - run: cd ~/mms && sleep 1m
      - run: cd ~/mms && docker network ls
      - run: cd ~/mms && docker network inspect mms_default
      - run: cd ~/mms && docker ps
      - run: docker inspect mms_mms_1 
      - run: docker inspect mms_postgres_1
      - run: docker inspect mms_elasticsearch_1
      #- run: cd ~/mms && docker run --network container:mms_mms_1 appropriate/curl --connect-timeout 30 --retry 300 --retry-delay 10 --retry-connrefused http://localhost:8080
     # - run cd ~/mms && docker exec mms_mms_1 curl --retry 30 --retry-delay 10 --retry-connrefused http://localhost:8080
      - run: 
          command: 
            cd ~/mms/example
            sudo npm install -g newman
            newman run crud.postman_collection.json -e test-env.json --delay-request 300
     #docker cp mms_mms_1:~/example/test-env.json /etc/newman
     #docker cp ~/mms/example/test-env.json mms_mms_1:/etc/newman
     #docker cp mms_mms_1:/example/test-env.json ~/mms/example/
     #
     # create a dummy container which will hold a volume with config
    #docker create -v /cfg --name configs alpine:3.4 /bin/true
    # copy a config file into this volume
    #docker cp path/in/your/source/code/app_config.yml configs:/cfg
    # start an application container using this volume
    #docker run --volumes-from configs app-image:1.2.3
    #docker pull postman/newman
    #docker create -v /mms/tst --name test mms_mms:latest /bin/true
     # - run: 
      #    command: |
       #     docker cp mms_mms_1:/mms/example/test-env.json ~/example/
       #     cd ~/mms/example
        #    docker run -v ~/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
      #- run: cd ~/mms; docker pull postman/newman
      #- run: cd example; docker pull postman/newman; docker run --network="bridge" -v ~/mms/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
#        - run: 
 #         command: | 
  #            docker pull postman/newman
  #            cd ~/mms/example
   #           docker run -v ~/mms/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300