version: 2.1
#orbs:
  #node: circleci/node@1.1.6
  #newman: postman/newman@0.0.2
jobs:
    build: 
        machine: true
        working_directory: ~/mms
        steps:
            - checkout
            - run: 
                name: "Install Docker Compose"
                working_directory: ~/mms
                command: |
                    set -x
                    sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
            - run:
                name: "Build and Run Containers and Newman Tests"
                working_directory: ~/mms
                command: | 
                    cd ~/mms && cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
                    cd ~/mms && docker-compose up --build -d
                    cd ~/mms && ./gradlew clean
                    cd ~/mms && sleep 3m
                    docker pull postman/newman && cd ~/mms/example && docker run -v ~/mms/example:/etc/newman -t postman/newman run crud.postman_collection.json -e test-env.json --delay-request 300
    #test:
        #executor:
            #name: newman/postman-newman-docker
        #steps:
          #- checkout
          #- run: sleep 3m
          #- run: cd example
          #- newman/newman-run: 
              #collection: example/crud.postman_collection.json
              #environment: example/test-env.json
              #delay-request: '300'
workflows:
    version: 2
    build-and-test:
      jobs:
        - build
        #- test
            #requires:
               # - build 