version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Create and start all services from the docker-compose configuration."
          command: |
            cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
            docker-compose build
            docker-compose run -d --name mms_mms_1 mms
      - run: sleep 30s
      - run: 
          name: "Run and test Postman Collection."
          command: |
            cd ~/mms/example
            IP_VAR=`docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mms_mms_1`
            sed -i "s/localhost/$IP_VAR/" test-env.json
            docker create -v /tst --name mms_test_configs alpine:3.4 /bin/true
            docker cp ~/mms/example/. mms_test_configs:/tst
            docker run --volumes-from mms_test_configs --link mms_mms_1 --network=mms_default -t postman/newman run /tst/crud.postman_collection.json -e /tst/test-env.json --delay-request 300
  deploy_artifacts:
    - run:
        name: Get jfrog
        command: curl -fL https://getcli.jfrog.io | sh
    - run:
        name: Set Permissions
        command: sudo chmod +x jfrog
    - run:
        name: Configure jfrog
        command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive false
    - run:
        name: Send mms-amp
        command: ./jfrog rt u 'mms-ent/repo-amp/target/*.amp' libs-release-local/gov/nasa/jpl/mms/mms-amp/3.4.2/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
    - run:
        name: Send mms-share-amp
        command: ./jfrog rt u 'mms-ent/share-amp/target/*.amp' libs-release-local/gov/nasa/jpl/mms/mms-share-amp/3.4.2/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
    - run:
        name: Send mms java client
        command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-java-client/mms-java-*.jar' libs-release-local/org/openmbee/mms/mms-java-client/3.4.2/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
    - run:
        name: Send mms python client
        command: ./jfrog rt u 'mms-ent/repo-amp/target/mms_python_*.zip' libs-release-local/gov/nasa/jpl/mms/mms-python-client/3.4.2/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
    - run:
        name: Send mms mathematica client
        command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-mathematica-*.zip' libs-release-local/gov/nasa/jpl/mms/mms-mathematica-client/3.4.2/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true
    - run:
        name: Send mms matlab client
        command: ./jfrog rt u 'mms-ent/repo-amp/target/mms-matlab-*.zip' libs-release-local/gov/nasa/jpl/mms/mms-matlab-client/3.4.2/ --build-name=mms-circleci --build-number=$CIRCLE_BUILD_NUM --flat=true     
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
    deploy-artifacts:
      jobs:
        - deploy-artifacts