version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/mms
    steps:
      - checkout
      - setup_remote_docker
      - run: cd ~/mms && cp example/src/main/resources/application.properties.example ./example/src/main/resources/application.properties
      - run: cd ~/mms && docker-compose up --build -d 
      #- run: cd ~/mms && sleep 2m
      - run: cd ~/mms && docker-compose ps
      #- run: cd ~/mms && DOCKER_HOST=mms_default:host
      - run: docker stop mms_mms_1 mms_elasticsearch_1 mms_postgres_1
      #_mms_1 mms_elasticsearch_1 mms_postgres_1
      - run: docker rm mms_mms_1 mms_elasticsearch_1 mms_postgres_1
      - run: cd ~/mms && docker-compose run -d -p 127.0.0.1:8080 mms --network=host
      - run: cd ~/mms && sleep 2m
      #- run: cd ~/mms && docker network connect host mms_mms_1
      - run: cd ~/mms && docker network ls
     # - run: cd ~/mms && docker network inspect host
      - run: cd ~/mms && docker-compose ps
      #- run: cd ~/mms && docker-compose logs -f --details mms_mms
      #- run: cd ~/mms && docker ps
      #- run: cd ~/mms && DOCKER_HOST=127.0.0.1:8080 
      - run: cd ~/mms && sudo npm install -g newman
      - run: cd ~/mms/example && newman run crud.postman_collection.json -e test-env.json --delay-request 300
workflows:
    build-and-test:
      jobs:
        - build-and-test